name: Create GitHub Issue

on:
  repository_dispatch:
    types: [create_issue]

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Issue
        uses: actions/github-script@v5
        with:
          script: |
            const issueTitle = context.payload.client_payload.title;
            const issueBody = context.payload.client_payload.body;
            const response = await github.issues.create({
              owner: 'Mountea-Framework',  // Do I need to provide organization?
              repo: 'MounteaDialoguer',
              title: issueTitle,
              body: issueBody,
            });
